# This file contains the secrets injected into the Ansible configuration.
#
# The secrets are added to the existing Ansible variables by adding this file to the command line:
#   ansible-playbook -i inventories/local_development -e @/path/to/this/file/secrets-local.yaml site_provision.yml
#

secrets:
  # database password for `qvain` user in Postgresql
  #
  # create with:
  #   DBUSER=qvain; DBPASS=fjkl0923sqpxk; echo -n md5; echo -n $DBPASS$DBUSER | md5sum | cut -d' ' -f1
  # or see:
  #   https://github.com/wvh/psqlpass
  db:
    password: fjkl0923sqpxk
    hashed: md590bd8782ed7d5cdb4d1e8d9acccef7c9
  # external apis
  apis:
    # 32 byte random key in hex for Qvain crypto
    #
    # generate with:
    #   openssl rand -hex 32
    token_key: 1e2e75f9f86eab4d48a167ffb91cef0da314dd31a07fe33e5a397b24ba2593f6
    # user and pass for Qvain to use the Metax API; ask from Hannu
    metax_api_user: qvain
    metax_api_pass: ask_from_hannu
    # id and secret for OpenID Connect in Fairdata authentication proxy; talk to AAI people
    oidc_provider_name: fairdata
    oidc_provider_url: https://fd-auth.csc.fi
    oidc_client_id: qvain.csc.local
    oidc_client_secret: ask_from_aai

# ssh user for Ansible deployment; not needed for local development, where it's hardcoded to `vagrant`
# ssh_user: cloud-user
